apiVersion: apps/v1 #k8s api  version
kind: Deployment # kiểu resoure cần deploy
metadata:
  name: angular-ocs
spec:
  selector:
    matchLabels:
      app: angular-ocs
  replicas: 2
  template:
    metadata:
      labels:
        app: angular-ocs
    spec:
      containers: 
      - name: angular
        image: docker30041999/ocs-prepare:2.0
        ports:
        - containerPort: 81
---
apiVersion: v1
kind: Service
metadata:
  name: angular-ocs
spec:
  selector:
    app: angular-ocs
  ports:
  - protocol: TCP
    port: 4300 # port service chay trên cluster
    targetPort: 80 #port expose bởi service
  type: LoadBalancer
